_BASE_: "diffdet.coco.swinbase.yaml"
MODEL:
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("insegcat_train",)
  TEST:  ("insegcat_test",)
SOLVER:
  IMS_PER_BATCH: 12
  AMP:
    ENABLED: True
  OPTIMIZER: "ADAMW"    
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 2000
  BASE_LR: 2e-6
  LR_SCHEDULER_NAME: WarmupCosineLR
  # Default scheduler name: WarmupMultiStepLR
  # correspoinding scheduler: MultiStepParamScheduler.
  # It can be combined with AdamW optimizer.
  # STEPS: (1000020000, 25000)
  # The default GAMMA is 0.1.
  # GAMMA: 0.2
  MAX_ITER: 30000
TEST:
  EVAL_PERIOD: 2000
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)

  FORMAT: "RGB"
