_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("insegcat_train",)
  TEST:  ("insegcat_test",)
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 2000
  BASE_LR: 2e-6
  LR_SCHEDULER_NAME: WarmupCosineLR
  # Default scheduler name: WarmupMultiStepLR
  # correspoinding scheduler: MultiStepParamScheduler.
  # It can be combined with AdamW optimizer.
  # STEPS: (1000020000, 25000)
  # The default GAMMA is 0.1.
  # GAMMA: 0.2
  MAX_ITER: 30000
TEST:
  EVAL_PERIOD: 2000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
