_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("insegcat_train",)
  TEST:  ("insegcat_test",)
SOLVER:
  STEPS: (1000, 1500)
  # The default GAMMA is 0.1.
  GAMMA: 0.2
  MAX_ITER: 2000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
